#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    relativenumber = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    windows_leader = "s"
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    disabled_plugins = ["denite.nvim, leaderf"]

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"
auto-completion-return-key-behavior = "smart"
auto-completion-complete-with-key-sequence = "jk"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30


[[layers]]
name = 'exprfold'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#xml'

[[layers]]
name = 'git'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'unite'

[[layers]]
name = 'markdown'

[[layers]]
name = 'chinese'

[[layers]]
name = 'tools'


[[layers]]
name = 'tags'


[[layers]]
name = 'colorscheme'


[[layers]]
name = 'lang#kotlin'


[[layers]]
  name = "lsp"
  filetypes = [
    "java"
  ]
  [layers.override_cmd]
    java = [
    "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx1G",
    "-jar", 
    "/home/qianz/.SpaceVim.d/features/org.eclipse.equinox.executable_3.8.500.v20190715-1310.jar",
    "-configuration",
    "/home/qianz/.SpaceVim.d/config_linux",
    "-data",
    "/home/qianz/.cache/javalsp"
    ]

[[custom_plugins]]
name = 'tbodt/deoplete-tabnine'


[[custom_plugins]]
    name = "SpaceVim/denite.nvim"
    merged = false
    loadconf = true

