#============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    default_indent = 4
    enable_guicolors = true
    autocomplete_method = 'coc'
    enable_debug = true
    enable_googlesuggest = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    enable_neomake = false
    statusline_unicode_symbols = true
    relativenumber = false
    enable_statusline_bfpath = true
    enable_statusline_tag = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    windows_leader = "s"
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    disabled_plugins = ["denite.nvim, leaderf"]
    # enable_vimfiler_gitstatus = true
    # filetree_direction = "left"
    enable_vimfiler_welcome = false
    checkinstall = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "smart"
auto-completion-tab-key-behavior = "cycle"
auto-completion-complete-with-key-sequence = "jk"

[[layers]]
name = 'shell'
default_height = 30


[[layers]]
name = 'exprfold'
enable = false

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#xml'

[[layers]]
name = 'git'
git-plugin = 'fugitive'

[[layers]]
name = 'checkers'
enable = false

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'unite'
enable = false

[[layers]]
name = 'denite'

[[layers]]
name = 'tmux'
tmux_navigator_modifier = "alt"

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'chinese'

[[layers]]
name = 'tools'


[[layers]]
name = 'gtags'


[[layers]]
name = 'colorscheme'
enable = false


[[layers]]
name = 'lang#kotlin'


[[layers]]
name = 'ui'

[[layers]]
name = 'format'


[[layers]]
  name = "lsp"
  filetypes = [
    "java"
  ]
  [layers.override_cmd]
    java = [
    "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx1G",
    "-jar", 
    "/Users/mac/.SpaceVim.d/jdt-language-server-latest/features/org.eclipse.equinox.executable_3.8.500.v20190903-1802.jar",
    "-configuration",
    "/Users/mac/.SpaceVim.d/jdt-language-server-latest/config_mac",
    "-data",
    "/Users/mac/.cache/javalsp"
    ]


[[custom_plugins]]
    name = "SpaceVim/denite.nvim"
    merged = false
    loadconf = true

[[custom_plugins]]
name = 'luochen1990/rainbow'


[[custom_plugins]]
name = 'fisadev/vim-ctrlp-cmdpalette'


[[custom_plugins]]
name = 'kien/ctrlp.vim'

[[custom_plugins]]
name = 'roxma/vim-hug-neovim-rpc'


[[custom_plugins]]
name = 'roxma/nvim-yarp'


[[custom_plugins]]
name = 'dhruvasagar/vim-table-mode'

